import type { ImageAsset } from "@/types/content";

const CDN_ROOT = "https://cdn.prod.website-files.com/68c53ddd23c15ad134bd30b3";

function localImage(options: {
  alt: string;
  publicPath: string;
  sourceUrl: string;
  width: number;
  height: number;
  sizes?: string;
  loading?: "eager" | "lazy";
  priority?: boolean;
  note?: string;
}): ImageAsset {
  return {
    kind: "local",
    src: options.publicPath,
    alt: options.alt,
    width: options.width,
    height: options.height,
    publicPath: options.publicPath,
    sourceUrl: options.sourceUrl,
    sizes: options.sizes,
    loading: options.loading ?? (options.priority ? "eager" : "lazy"),
    priority: options.priority,
    note: options.note,
  };
}

export const siteImages = {
  zamTherapyMark: localImage({
    alt: "Zam Therapy brand mark",
    publicPath: "/images/brand/zam-therapy-round.png",
    sourceUrl: `${CDN_ROOT}/68f0d521fcdb02e82ddf48bf_Artboard%201.png`,
    width: 106,
    height: 116,
    sizes: "112px",
  }),
  homeHero: localImage({
    alt: "Sports Massage & Physiotherapy in Barnet",
    publicPath: "/images/home/home-hero.avif",
    sourceUrl: `${CDN_ROOT}/68e61ac91cc92077f07eb3f3_home%20hero%203.avif`,
    width: 2276,
    height: 1280,
    sizes: "100vw",
    loading: "eager",
    priority: true,
  }),
  homeServiceSportsMassage: localImage({
    alt: "Sports massage service card image",
    publicPath: "/images/home/service-sports-massage.avif",
    sourceUrl: `${CDN_ROOT}/68c5404cccc854a48bed7967_relume-378981.avif`,
    width: 2560,
    height: 1706,
    sizes: "(max-width: 768px) 100vw, 33vw",
  }),
  homeServicePhysiotherapy: localImage({
    alt: "Physiotherapy service card image",
    publicPath: "/images/home/service-physiotherapy.avif",
    sourceUrl: `${CDN_ROOT}/68e61f6c004f5c9be009886c_phsyio%20service.avif`,
    width: 2688,
    height: 1536,
    sizes: "(max-width: 768px) 100vw, 33vw",
  }),
  homeServiceHijama: localImage({
    alt: "Hijama service card image",
    publicPath: "/images/home/service-hijama.avif",
    sourceUrl: `${CDN_ROOT}/68e61f6cf6871d26ab6dfc23_hijama%20service.avif`,
    width: 2912,
    height: 4000,
    sizes: "(max-width: 768px) 100vw, 33vw",
  }),
  aboutZaheer: localImage({
    alt: "Zaheer seated in treatment room",
    publicPath: "/images/home/about-zaheer.avif",
    sourceUrl: `${CDN_ROOT}/68e61e34a2c42671abb439ac_Zaheer.avif`,
    width: 2048,
    height: 2048,
    sizes: "(max-width: 768px) 100vw, 40vw",
  }),
  painFreeMovement: localImage({
    alt: "Pain-free movement",
    publicPath: "/images/home/outcome-pain-free-movement.avif",
    sourceUrl: `${CDN_ROOT}/68e61e34dd34fda118010afd_man%20stretching.avif`,
    width: 2688,
    height: 1536,
  }),
  eliteRecovery: localImage({
    alt: "Elite recovery",
    publicPath: "/images/home/outcome-elite-recovery.avif",
    sourceUrl: `${CDN_ROOT}/68e61e3439dcc296776cc0f7_woman%20running%20hijab.avif`,
    width: 2688,
    height: 1536,
  }),
  reducedAnxiety: localImage({
    alt: "Reduced anxiety",
    publicPath: "/images/home/outcome-reduced-anxiety.avif",
    sourceUrl: `${CDN_ROOT}/68e61e344eb26d3789faa063_woman%20breathing.avif`,
    width: 2688,
    height: 1536,
  }),
  improvedPerformance: localImage({
    alt: "Improved performance",
    publicPath: "/images/home/outcome-improved-performance.avif",
    sourceUrl: `${CDN_ROOT}/68e61e336bb92e492c44091b_footballer.avif`,
    width: 2688,
    height: 1536,
  }),
  featuredHomeTestimonial: localImage({
    alt: "Featured testimonial portrait",
    publicPath: "/images/home/featured-testimonial.avif",
    sourceUrl: `${CDN_ROOT}/68e61e34b9ef626156cf20f1_man%20smiling%20in%20london.avif`,
    width: 2688,
    height: 1536,
  }),
  homeLargeTestimonial: {
    kind: "remote",
    src: `${CDN_ROOT}/68ec064c9d82abc580eb8181_zaheer%20massage%202.jpg`,
    alt: "Massage treatment testimonial image",
    width: 8192,
    height: 8192,
    sourceUrl: `${CDN_ROOT}/68ec064c9d82abc580eb8181_zaheer%20massage%202.jpg`,
    sizes: "(max-width: 768px) 100vw, 50vw",
    loading: "lazy",
    priority: false,
    note: "Temporary remote asset retained for visual parity until Phase 9 asset ownership cleanup.",
  },
  homeCtaMassage: localImage({
    alt: "Massage treatment close-up",
    publicPath: "/images/home/cta-massage.avif",
    sourceUrl: `${CDN_ROOT}/68e61e344a388380c2b3b40e_man%20on%20massage%20table.avif`,
    width: 4000,
    height: 2280,
    sizes: "100vw",
  }),
  sharedSessionPractitioner: localImage({
    alt: "Therapist during a consultation session",
    publicPath: "/images/shared/session-practitioner.avif",
    sourceUrl: `${CDN_ROOT}/68ca8e1f4f1b049e5e0315fa_freepik__a-medium-shot-of-a-black-man-25-years-old-with-sho__16624.avif`,
    width: 1248,
    height: 832,
    sizes: "(max-width: 768px) 100vw, 50vw",
  }),
  physiotherapyHeroPrimary: localImage({
    alt: "Physiotherapy in Barnet",
    publicPath: "/images/physiotherapy/hero-primary.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a3aa9817a9b9e16866e_physiotherapy%20hero%201.avif`,
    width: 2048,
    height: 2048,
    sizes: "(max-width: 768px) 100vw, 36vw",
    loading: "eager",
    priority: true,
  }),
  physiotherapyHeroSecondary: localImage({
    alt: "Physiotherapy in Barnet",
    publicPath: "/images/physiotherapy/hero-secondary.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a9aa560a2cc45386dbb_physiotherapy%20hero%202.avif`,
    width: 1728,
    height: 2368,
    sizes: "(max-width: 768px) 100vw, 32vw",
    loading: "eager",
    priority: true,
  }),
  physiotherapyPainRelief: localImage({
    alt: "Physiotherapy for pain relief",
    publicPath: "/images/physiotherapy/benefit-pain-relief.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a3b83d27763de550a5d_pain%20relief.avif`,
    width: 3000,
    height: 4000,
  }),
  physiotherapyBetterPosture: localImage({
    alt: "Physiotherapy for better posture",
    publicPath: "/images/physiotherapy/benefit-better-posture.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a3af5ae1034bfdbc475_better%20posture.avif`,
    width: 2048,
    height: 2048,
  }),
  physiotherapyInjuryRecovery: localImage({
    alt: "Physiotherapy for injury recovery",
    publicPath: "/images/physiotherapy/benefit-injury-recovery.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a3a46c6c49acfbc557b_injury%20recovery.avif`,
    width: 2688,
    height: 1536,
  }),
  physiotherapySportsPerformance: localImage({
    alt: "Physiotherapy for sports performance",
    publicPath: "/images/physiotherapy/benefit-sports-performance.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a39084c6ff8cf304202_ehanced%20sports%20performance.avif`,
    width: 1728,
    height: 2368,
  }),
  physiotherapyMobility: localImage({
    alt: "Physiotherapy for mobility",
    publicPath: "/images/physiotherapy/benefit-mobility.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a3bfde695e2a42e5004_restored%20mobility.avif`,
    width: 4000,
    height: 2288,
  }),
  physiotherapyStrength: localImage({
    alt: "Physiotherapy for strength and stability",
    publicPath: "/images/physiotherapy/benefit-strength.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a3a57ab063f765fac4b_improved%20strength.avif`,
    width: 2496,
    height: 1664,
  }),
  physiotherapyStoryFrozenShoulder: localImage({
    alt: "Frozen shoulder recovery story image",
    publicPath: "/images/physiotherapy/story-frozen-shoulder.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a9afed93d19bba51118_tennis%20player.avif`,
    width: 2048,
    height: 2048,
  }),
  physiotherapyStoryBackPain: localImage({
    alt: "Back pain relief story image",
    publicPath: "/images/physiotherapy/story-back-pain.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a3a6edf80d6adbbac2f_ofiice%20worker.avif`,
    width: 2048,
    height: 2048,
  }),
  physiotherapyStoryStressRelief: localImage({
    alt: "Stress relief story image",
    publicPath: "/images/physiotherapy/story-stress-relief.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a3a40696984c0f18481_running%20man.avif`,
    width: 2048,
    height: 2048,
  }),
  physiotherapyCta: localImage({
    alt: "Physiotherapy assistance",
    publicPath: "/images/physiotherapy/cta-assistance.avif",
    sourceUrl: `${CDN_ROOT}/68ef4afed1abca87a5945767_phsyio%20massage.avif`,
    width: 2688,
    height: 1536,
    sizes: "100vw",
  }),
  physiotherapyOutcomes: {
    kind: "remote",
    src: `${CDN_ROOT}/68ef4887ac74e051fd6489be_physio%20assistance.avif`,
    alt: "Physiotherapy assistance",
    width: 2048,
    height: 2048,
    sourceUrl: `${CDN_ROOT}/68ef4887ac74e051fd6489be_physio%20assistance.avif`,
    sizes: "(max-width: 2048px) 100vw, 2048px",
    loading: "lazy",
    priority: false,
    note: "Temporary remote asset retained for Phase 6 visual parity until Phase 9 asset ownership cleanup.",
  },
  sportsMassageHero: localImage({
    alt: "Sports massage hero treatment",
    publicPath: "/images/sports-massage/hero-primary.avif",
    sourceUrl: `${CDN_ROOT}/68ec0ea95f0d8294cf4410ae_massaege%20hero%201.avif`,
    width: 2688,
    height: 1536,
    sizes: "(max-width: 768px) 100vw, 52vw",
    loading: "eager",
    priority: true,
  }),
  sportsMassageHeroSecondary: localImage({
    alt: "Sports massage treatment close-up",
    publicPath: "/images/sports-massage/hero-secondary.avif",
    sourceUrl: `${CDN_ROOT}/68ebfdd87f3527a5a308a18b_zaheer%20massage.avif`,
    width: 1728,
    height: 2368,
    sizes: "(max-width: 768px) 100vw, 36vw",
    loading: "eager",
    priority: true,
  }),
  sportsMassageTension: localImage({
    alt: "Relief from chronic tension",
    publicPath: "/images/sports-massage/benefit-tension.avif",
    sourceUrl: `${CDN_ROOT}/68ec0eaa163dd25286bdf0da_runner%20in%20pain.avif`,
    width: 4000,
    height: 4000,
  }),
  sportsMassageRecovery: localImage({
    alt: "Faster workout recovery",
    publicPath: "/images/sports-massage/benefit-recovery.avif",
    sourceUrl: `${CDN_ROOT}/68ec0ea9a6dffe801454f80f_stretching%20man.avif`,
    width: 2048,
    height: 2048,
  }),
  sportsMassagePain: localImage({
    alt: "Reduced muscle pain",
    publicPath: "/images/sports-massage/benefit-pain.avif",
    sourceUrl: `${CDN_ROOT}/68ec0ea9b2a7949815373c17_hiker.avif`,
    width: 2048,
    height: 2048,
  }),
  sportsMassageCirculation: localImage({
    alt: "Boosted circulation",
    publicPath: "/images/sports-massage/benefit-circulation.avif",
    sourceUrl: `${CDN_ROOT}/68ec0ea9852237fd98e0b47b_morning%20run%20watch.avif`,
    width: 2048,
    height: 2048,
  }),
  sportsMassageExpectations: localImage({
    alt: "Sports massage expectations image",
    publicPath: "/images/physiotherapy/benefit-sports-performance.avif",
    sourceUrl: `${CDN_ROOT}/68ec0a39084c6ff8cf304202_ehanced%20sports%20performance.avif`,
    width: 1728,
    height: 2368,
  }),
  sportsMassageStoryRunnerRecovery: localImage({
    alt: "Runner recovery story image",
    publicPath: "/images/sports-massage/story-runner-recovery.avif",
    sourceUrl: `${CDN_ROOT}/68ec0ea9b57220ccd37e99ac_morning%20running%20man.avif`,
    width: 2048,
    height: 2048,
  }),
  sportsMassageStoryLowerBackRelief: localImage({
    alt: "Lower back relief story image",
    publicPath: "/images/sports-massage/story-lower-back-relief.avif",
    sourceUrl: `${CDN_ROOT}/68ec10f0ea5510492ca6a6dd_factory%20worker.avif`,
    width: 2048,
    height: 2048,
  }),
  sportsMassageStorySleepImprovement: localImage({
    alt: "Sleep improvement story image",
    publicPath: "/images/sports-massage/story-sleep-improvement.avif",
    sourceUrl: `${CDN_ROOT}/68ec10efb3c5519681b39978_happy%20morning.avif`,
    width: 2048,
    height: 2048,
  }),
  sportsMassageCta: localImage({
    alt: "Sports massage call to action image",
    publicPath: "/images/sports-massage/cta-kickboxer.avif",
    sourceUrl: `${CDN_ROOT}/68ef5068610235baba04e5c4_kickboxer.avif`,
    width: 2688,
    height: 1536,
    sizes: "100vw",
  }),
  hijamaHero: localImage({
    alt: "Hijama hero treatment",
    publicPath: "/images/hijama/hero-primary.avif",
    sourceUrl: `${CDN_ROOT}/68ec136216529559bfba0fee_hijama%20hero%201.avif`,
    width: 4000,
    height: 4000,
    sizes: "(max-width: 768px) 100vw, 52vw",
    loading: "eager",
    priority: true,
  }),
  hijamaHeroCloseup: localImage({
    alt: "Hijama treatment close-up",
    publicPath: "/images/hijama/hero-secondary.avif",
    sourceUrl: `${CDN_ROOT}/68ec1362852237fd98e15a03_hijama%20closeup.avif`,
    width: 4000,
    height: 4000,
    sizes: "(max-width: 768px) 100vw, 36vw",
    loading: "eager",
    priority: true,
  }),
  hijamaPainRelief: localImage({
    alt: "Relief from chronic pain",
    publicPath: "/images/hijama/benefit-pain-relief.avif",
    sourceUrl: `${CDN_ROOT}/68ec1361d86f60bfd8b3bc6f_woman%20yoga.avif`,
    width: 1728,
    height: 2304,
  }),
  hijamaDetox: localImage({
    alt: "Detox and cleansing",
    publicPath: "/images/hijama/benefit-detox.avif",
    sourceUrl: `${CDN_ROOT}/68ec1361eb66973be6d71758_detox.avif`,
    width: 2048,
    height: 2048,
  }),
  hijamaCirculation: localImage({
    alt: "Better circulation",
    publicPath: "/images/hijama/benefit-circulation.avif",
    sourceUrl: `${CDN_ROOT}/68ec13618c6ea768a6e79bb7_morning%20run%202.avif`,
    width: 2048,
    height: 2048,
  }),
  hijamaStoryFatigueEnergy: localImage({
    alt: "Fatigue to energy story image",
    publicPath: "/images/hijama/story-fatigue-energy.avif",
    sourceUrl: `${CDN_ROOT}/68ec136112e0101f4d5c7811_happy%20worker.avif`,
    width: 2048,
    height: 2048,
  }),
  hijamaStoryHeadachesStress: localImage({
    alt: "Headaches and stress relief story image",
    publicPath: "/images/hijama/story-headaches-stress.avif",
    sourceUrl: `${CDN_ROOT}/68ec13614b2db85552792a84_cafe%20man.avif`,
    width: 2048,
    height: 2048,
  }),
  hijamaStoryBackPainRelief: localImage({
    alt: "Hijama back pain relief story image",
    publicPath: "/images/hijama/story-back-pain-relief.avif",
    sourceUrl: `${CDN_ROOT}/68ef4f8d2fae8a78cf0a68f6_plumber.avif`,
    width: 2048,
    height: 2048,
  }),
  hijamaCta: localImage({
    alt: "Hijama benefits image",
    publicPath: "/images/hijama/cta-benefits.avif",
    sourceUrl: `${CDN_ROOT}/68ef5191c3a3f9bcb1d17875_hijama%20benefits.avif`,
    width: 2048,
    height: 2048,
    sizes: "100vw",
  }),
} as const satisfies Record<string, ImageAsset>;

export type SiteImageKey = keyof typeof siteImages;

export function getSiteImage(key: SiteImageKey) {
  return siteImages[key];
}
