ALTER TABLE public.availability_overrides
  DROP CONSTRAINT IF EXISTS availability_overrides_override_date_key;
ALTER TABLE public.staff_availability_overrides
  DROP CONSTRAINT IF EXISTS staff_availability_overrides_staff_id_override_date_key;